### ISSUE TITLE
port to python 3 (commandline only)

### ISSUE THREAD

**Issue by stefanfoulis** [petersilva/drobo-utils#1] opened 2020-12-31 10:45 UTC
After I upgraded to ubuntu 20.10 and realised I can't just `apt-get install drobo-utils` anymore.
In the readme you list that the tool is abandoned because it uses an outdated library (`qt4`) and that it still uses `python2`. Thanks a lot for supporting this tool over the years, very much appreciated 🤗 .

I was wondering how much effort it might be to port the command line part of drobo-utils to python3 (I may be able to do it).

It looks like all the code needed for command line usage is in `Drobo.py`, `DroboIOctl.py` and `drobom` 🤔.
`DroboIOctl.py` is using `ctypes` (which I've never used before, so scares me a little bit).

Does the command line part have any dependencies besides python3?
Where do you see other potential porting problems?

**Comment by petersilva** [comment] 2021-01-01 07:13
I made an issue001 branch, wirh a  first shot at a python3 port.  Give it a shot.
It is as you describe... no GUI.

**Comment by petersilva** [comment] 2021-01-01 17:42
I ported the GUI now... so it will start up (using qt 5 now instead of qt4) but no idea whether it really works... cli or gui.
it just does not crash when I run it.  it was just run through 2to3 for the initial port... it might have some bad understandings.
You are likely to get some weird errors. Please don't use on any valuable data... just for testing for now.

**Comment by petersilva** [comment] 2021-01-01 18:10
To use it... you need to be familiar with git.
You might have to install python3-qt5 or pyside something... I used qt5

```
sudo apt install python3-qtpy python-qt5
git clone https://github.com/petersilva/drobo-utils
git checkout issue001
./drobom -v 128 status
./drobom -v 128 view

```
128 is a simulation mode... does not actually query any drobos.  It just runs the code.
You will likely find errors when you try to get it probe actual drobos.  send me error messages, I can likely debug it fairly easily.

**Comment by petersilva** [comment] 2021-01-01 18:28
ugh... the debian packaging is also broken... being too old... not obvious how to port that to modern stuff either.
python-support is removed... need to use python-central?

**Comment by JaggedJax** [comment] 2021-01-05 00:17
Since I ran across this I tried running the status command against an actual drobo and received this output:
```
Traceback (most recent call last):
  File "drobom", line 316, in <module>
    l = Drobo.DiscoverLUNs(debug,vendor_string)
  File "/home/william/drobo-utils/Drobo.py", line 1427, in DiscoverLUNs
    for potential in DroboIOctl.drobolunlist(DEBUG,vendorstring):
  File "/home/william/drobo-utils/DroboIOctl.py", line 322, in drobolunlist
    if ( id[4].lower().startswith("trusted") or \
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
So it looks like id[4] needs to be cast to a string. 

Then after that I get:

```
Traceback (most recent call last):
  File "drobom", line 316, in <module>
    l = Drobo.DiscoverLUNs(debug,vendor_string)
  File "/home/william/drobo-utils/Drobo.py", line 1427, in DiscoverLUNs
    for potential in DroboIOctl.drobolunlist(DEBUG,vendorstring):
  File "/home/william/drobo-utils/DroboIOctl.py", line 343, in drobolunlist
    pdio.closefd()
  File "/home/william/drobo-utils/DroboIOctl.py", line 111, in closefd
    if self.sg_fd > 0:
TypeError: '>' not supported between instances of '_io.TextIOWrapper' and 'int'
```

**Comment by petersilva** [comment] 2021-01-05 01:11
Plugged the drobo on my shelf into my ubuntu 20.04:

```
fractal% sudo ./drobom status
/dev/sda - Drobo disk pack 00% full - ([], 0)
fractal% sudo ./drobom info
---------------------------------------------------------
Drobo Name: Drobo disk pack Devices: /dev/sda
      Time: Wed Dec 31 19:02:25 1969
---------------------------------------------------------
Configuration maxima: slots: 4, luns: 16, lunsize: 2 TB
Capacity (in GB):  used: 0, free: 493, total: 493
protocol version:  0.11
SCSI emulation information:
Vendor: TRUSTED   Model: Mass Storage     Revision: 1.00
/dev/sda: bus=scsi6 channel=0 id=0 lun=0 (vendor=TRUSTED , version=30527)
query slotinfo result:  number of slots: 4
slot   GB                Model               Status
   0    0                                      gray
   1    0                                      gray
   2  500          ST3500830AS                green
   3  500          ST3500830AS                green
Firmware: 1.3.5
Revision: 1.252 ( 21110 ) built: Aug 31 2009,18:12:03
Features: NO_AUTO_REBOOT,NO_FAT32_FORMAT,USED_CAPACITY_FROM_HOST,DISKPACKSTATUS,ENCRYPT_NOHEADER,CMD_STATUS_QUERIABLE,VARIABLE_LUN_SIZE_1_16,PARTITION_LUN_GPT_MBR,FAT32_FORMAT_VOLNAME,SUPPORTS_DROBOSHARE,SUPPORTS_NEW_LUNINFO2,feature x0800,feature x2000
/dev/sda - Drobo disk pack 00% full - ([], 0)
	RedThreshold 95
	YellowThreshold 85
lun     size (GB) used    PTFmt  FStype:
  0     2199         0  No Partitions ['NO FORMAT'] 
---------------------------------------------------------
fractal%
fractal% sudo ./drobom fwcheck
looking for firmware for: armmarvell 1.252.21110 hw version: 1.00
This Drobo should be running:  raptor/firmware/armmarvell/v1.3.7.tdz
raptor/firmware/armmarvell/v1.3.7.tdz
fractal%
```

which I guess means it is working for me... sort of...

**Comment by petersilva** [comment] 2021-01-05 01:31
ugh never mind... was running earlier version with python2.  reproduced the issue easily.

**Comment by petersilva** [comment] 2021-01-05 03:14
working a bit better now (git pull and try again...)  still some stuff that does not work.  partitioned and mkfs worked fine.
but firmware check and upgrade still busted. pretty much everything else works... espcially blinking lights... those are crucial ;-)

**Comment by petersilva** [comment] 2021-01-05 04:47
firmware check and firmware upgrade still broken.

**Comment by petersilva** [comment] 2021-01-05 14:08
status of branch:

* port to python3, QT5, dh-python completed.  packaging is working.
* GUI works fine, but dumps core on exit (no idea why.)
* blink, shutdown, work fine. status queries seems fine.
* broken: dumping diagnostics, fwcheck, fwupgrade.

**Comment by petersilva** [comment] 2021-01-05 14:23
* turned the broken features into separate bug reports, merged existing code to main.

**Closed as completed by petersilva** 2021-01-05 14:23 UTC

**Comment by stefanfoulis** [comment] 2021-09-19 12:23
the readme in the `main` branch talks about a `python3/qt5/dh-python` branch for ubuntu 20.04 and python3. Since this seems merged now that text is outdated, right?

**Comment by petersilva** [comment] 2021-09-19 13:09
true... I guess I should remove that... since the port of that got done.

**Comment by petersilva** [comment] 2021-09-19 13:12
5db5c071a0d3aa967c1039d93a5b4727d23f4dbc clarified comment.
